services:
  app:
    image: kevinlee-06/linklie
    ports:
      - 8080:8080
      - ${PORT}:8080
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - db_data:/data/db

volumes:
  db_data:

  # run `docker build -t kevinlee-06/linklie .` to build the image first