services:
  app:
    build: .
    ports:
      - ${PORT}:8080
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - db_data:/data/db

volumes:
  db_data: